export const questions = [
"What is a small thing that consistently makes your day better?",
"If you could have any animal as a perfectly tamed pet, what would you choose?",
"What is the most memorable meal you have ever eaten?",
"If you could be an expert in any musical instrument overnight, which would it be?",
"What is a hobby you have always wanted to pick up but never got around to?",
"If you were a color, which one would best represent your personality today?",
"What is the most interesting piece of trivia you know?",
"If you could witness any natural phenomenon in person, what would it be?",
"What is a movie or book you can enjoy over and over again?",
"If you had to describe your sense of humor using only three words, what would they be?",
"What is a lesson you learned the hard way that you are now grateful for?",
"If you could revisit one specific moment in your past just to observe it, what would it be?",
"What is a tradition or habit you started for yourself?",
"If you could have a conversation with your younger self, what piece of advice would you give?",
"What is the most beautiful place you have ever seen with your own eyes?",
"How has your taste in music or art changed as you have grown older?",
"What is a challenge you overcame that made you feel proud of yourself?",
"If you could see a video of any one event from your life, which would you pick?",
"What is a skill you possess that people might not expect you to have?",
"How do you usually like to spend a completely free afternoon?",
"What do you think is the most important quality for a person to have?",
"If you could change one thing about how the world works, what would it be?",
"What is a popular trend that you never quite understood the appeal of?",
"How do you define success for yourself personally?",
"What do you think is the most underrated virtue in modern society?",
"If you could make one rule that everyone in the world had to follow for a day, what would it be?",
"What is an opinion you hold that most people seem to disagree with?",
"How much do you think a person’s environment shapes who they become?",
"What do you think is the best way to resolve a disagreement between friends?",
"If you could ask a person from 100 years in the future one question, what would it be?",
"If you could pause time for everyone but yourself for one hour a day, how would you use it?",
"What would you do if you discovered you were the only person left on Earth for 24 hours?",
"If you could design a new planet from scratch, what would be its most unique feature?",
"How would the world change if humans no longer needed to sleep?",
"If you could communicate with one species of plant, what do you think they would say?",
"What would you do if you found a door that led to a different dimension in your home?",
"If you could trade one year of your life for a guaranteed talent, would you do it?",
"How would society be different if people could actually feel each other's physical pain?",
"If you could live in a world where it was always daytime or always nighttime, which would you choose?",
"What would you do if you could suddenly speak every human language fluently?",
"What is a goal you are currently working toward, no matter how small?",
"How do you stay motivated when things get difficult or repetitive?",
"What is a habit you are trying to build or break right now?",
"If you could master any new skill in a single week, what would it be?",
"How do you personally handle the feeling of being overwhelmed?",
"What does 'finding balance' look like in your daily life?",
"What is a quality in someone else that you genuinely admire?",
"How has your perspective on what matters most changed in the last few years?",
"What is a fear you have faced that made you stronger?",
"If you could be remembered for one specific character trait, what would it be?",
"If you could invent a new holiday, what would it celebrate?",
"What would the theme song of your current life phase sound like?",
"If you were tasked with building a time capsule for the year 3000, what would you put in it?",
"Which fictional character do you relate to the most?",
"If you could design a dream house without worrying about the laws of physics, what would it include?",
"What is a story you would love to write if you were a famous author?",
"If you could create a new flavor of ice cream, what would the ingredients be?",
"What kind of art would you create if you had unlimited resources and space?",
"If you could change the ending of any movie, which one would it be and how?",
"What would your personal utopia look like?",
"What is the most rewarding part of the work or projects you do?",
"If you could switch careers or fields of study for a month just for fun, what would you try?",
"What is the best piece of professional or academic advice you have ever received?",
"How do you prefer to organize your thoughts when you have a big task ahead?",
"What is a tool or piece of equipment that makes your life significantly easier?",
"How do you stay focused in a world full of distractions?",
"What is a project you finished that you are particularly proud of?",
"If you could teach a class on any topic you know well, what would the title be?",
"What is the most interesting thing you have learned recently?",
"How do you like to reward yourself after accomplishing a difficult task?",
"What do you think is the most positive impact the internet has had on society?",
"If you could delete one social media platform forever, which would it be?",
"How do you find a balance between staying informed and protecting your peace of mind?",
"What is a piece of technology you use every day that still feels like magic to you?",
"If you could have a robotic assistant to do one specific chore, what would you delegate?",
"How do you think the way we communicate will change in the next twenty years?",
"What is your favorite way to 'unplug' from the digital world?",
"If you could see a graph of any statistic from your life, what would you want to track?",
"What do you think is the most helpful website or app that nobody knows about?",
"How has the internet changed the way you learn new things?",
"What is the best piece of advice you’ve ever given to someone else?",
"If you could spend a day as any person from history, who would you choose?",
"What is something you think everyone should experience at least once in their life?",
"How do you decide when to take a risk and when to play it safe?",
"What is a book that changed the way you think about the world?",
"If you could have any view from your window every morning, what would it be?",
"What do you think is the most important invention of all time?",
"How do you personally define what it means to be a 'good' person?",
"If you could be any age forever, which age would you choose?",
"What is a question you wish people would ask you more often?",
"What is the most peaceful sound you can think of?",
"If you could live in any era of the past for one week, which would it be?",
"What is a mystery you would love to see solved in your lifetime?",
"How do you like to decorate your personal space to make it feel like home?",
"What is a small act of kindness you witnessed that stayed with you?",
"If you could instantly become an expert in any language, which would you choose?",
"What do you think is the most important lesson children can learn?",
"If you could change your first name to anything else, what would it be?",
"What is a scent that brings back a very specific memory for you?",
"If you could have the answer to any one question in the universe, what would you ask?",
]